In [30]:
import numpy as np
import pandas as pd
import sklearn.datasets      
from KNNClassifier_Algorithm import KNNClassifier      # importing the custom KNN class
import sklearn.model_selection       # for train test split
from sklearn import metrics as m       # for accuracy calculation
from sklearn.metrics import confusion_matrix

In [31]:
dataset = sklearn.datasets.load_iris() #Iris Dataset
X = dataset.data # extracting data points
y = dataset.target # extracting labels

In [32]:
iris_data= pd.DataFrame(data= np.c_[dataset['data'], dataset['target']],
                     columns= dataset['feature_names'] + ['target'])
iris_data.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
count,150.000000,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333,1.000000
std,0.828066,0.435866,1.765298,0.762238,0.819232
min,4.300000,2.000000,1.000000,0.100000,0.000000
25%,5.100000,2.800000,1.600000,0.300000,0.000000
50%,5.800000,3.000000,4.350000,1.300000,1.000000
75%,6.400000,3.300000,5.100000,1.800000,2.000000
max,7.900000,4.400000,6.900000,2.500000,2.000000

In [33]:
X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(X, y, test_size=0.30, train_size=0.70)

Custom KNN Classifier

In [50]:
k = KNNClassifier(k_neighbors=4) # creating an object of custom KNN class with k=4
k.fit(X_train, y_train); # a custom function to fit the TR data is called.
CustomKNNClassifierPrediction = k.predict(X_test); # a custom function to predict the labels of TE data is called.

In [35]:
m.accuracy_score(y_test, CustomKNNClassifierPrediction) # calculating accuracy of custom KNN classifier

0.9777777777777777

In [36]:
conf_matrix_Custom_KNN_Dataset1 = confusion_matrix(y_test, CustomKNNClassifierPrediction)
df = pd.DataFrame(conf_matrix_Custom_KNN_Dataset1, index=["Actual_0", "Actual_1", "Actual_2"], columns=["Pred_0", "Pred_1", "Pred_2"])
df.to_csv("Dataset1_Classifier1.csv")

SKLearn KNN Classifier

In [37]:
from sklearn.neighbors import KNeighborsClassifier
neighbor = KNeighborsClassifier(n_neighbors=3) # making an object of the sklearn KNNClassifier class
neighbor.fit(X_train, y_train) # training the object with TR 
prediction = neighbor.predict(X_test)
m.accuracy_score(y_test, prediction) # calculating accuracy of sklearn KNN classifier

0.9777777777777777

In [38]:
conf_matrix_SkLearn_KNN_Dataset1 = confusion_matrix(y_test, prediction)
df1 = pd.DataFrame(conf_matrix_SkLearn_KNN_Dataset1, index=["Actual_0", "Actual_1", "Actual_2"], columns=["Pred_0", "Pred_1", "Pred_2"])
df1.to_csv("Dataset1_Classifier2.csv")

 SKLearn Tree Classifier

In [39]:
from sklearn import tree
clf = tree.DecisionTreeClassifier() # making an object of the DecisionTreeClassifier class
clf = clf.fit(X_train, y_train) # training the object with TR
predictionDecisionTrees = clf.predict(X_test); # predicting the labels of TE data
m.accuracy_score(y_test, predictionDecisionTrees) # calculating accuracy of decision tree classifier

0.9555555555555556

In [40]:
conf_matrix_SkLearn_DecisionTrees_Dataset1 = confusion_matrix(y_test, predictionDecisionTrees)
df2 = pd.DataFrame(conf_matrix_SkLearn_DecisionTrees_Dataset1, index=["Actual_0", "Actual_1", "Actual_2"], columns=["Pred_0", "Pred_1", "Pred_2"])
df2.to_csv("Dataset1_Classifier3.csv")

 # Dataset Number 2 -> Wine Quality Dataset

In [41]:
dataset2 = sklearn.datasets.load_wine() #Wine Dataset
x1 = dataset2.data # extracting data points
y1 = dataset2.target # extracting labels
dataset_wine= pd.DataFrame(data= np.c_[dataset2['data'], dataset2['target']],
                     columns= dataset2['feature_names'] + ['target'])
dataset_wine.describe()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
count,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000
mean,13.000618,2.336348,2.366517,19.494944,99.741573,2.295112,2.029270,0.361854,1.590899,5.058090,0.957449,2.611685,746.893258,0.938202
std,0.811827,1.117146,0.274344,3.339564,14.282484,0.625851,0.998859,0.124453,0.572359,2.318286,0.228572,0.709990,314.907474,0.775035
min,11.030000,0.740000,1.360000,10.600000,70.000000,0.980000,0.340000,0.130000,0.410000,1.280000,0.480000,1.270000,278.000000,0.000000
25%,12.362500,1.602500,2.210000,17.200000,88.000000,1.742500,1.205000,0.270000,1.250000,3.220000,0.782500,1.937500,500.500000,0.000000
50%,13.050000,1.865000,2.360000,19.500000,98.000000,2.355000,2.135000,0.340000,1.555000,4.690000,0.965000,2.780000,673.500000,1.000000
75%,13.677500,3.082500,2.557500,21.500000,107.000000,2.800000,2.875000,0.437500,1.950000,6.200000,1.120000,3.170000,985.000000,2.000000
max,14.830000,5.800000,3.230000,30.000000,162.000000,3.880000,5.080000,0.660000,3.580000,13.000000,1.710000,4.000000,1680.000000,2.000000

Custom KNN Classifier

In [42]:
X1_train, x1_test, y1_train, y1_test = sklearn.model_selection.train_test_split(x1, y1, test_size=0.20, train_size=0.80,random_state=42)

In [43]:
k2 = KNNClassifier(k_neighbors=3) # creating an object of custom KNN class with k=3
k2.fit(X1_train, y1_train); # a custom function to fit the TR data is called.
CustomKNNClassifierPrediction2 = k2.predict(x1_test); # a custom function to

In [44]:
m.accuracy_score(y1_test, CustomKNNClassifierPrediction2) # calculating accuracy of custom KNN classifier

0.8055555555555556

In [45]:
conf_matrix_Custom_KNN_Dataset2 = confusion_matrix(y1_test, CustomKNNClassifierPrediction2)
df3 = pd.DataFrame(conf_matrix_Custom_KNN_Dataset2, index=["Actual_0", "Actual_1", "Actual_2"], columns=["Pred_0", "Pred_1", "Pred_2"])
df3.to_csv("Dataset2_Classifier1.csv")

SKLearn KNN Classifier

In [46]:
from sklearn.neighbors import KNeighborsClassifier
neigh1 = KNeighborsClassifier(n_neighbors=3) # making an object of the sklearn KNNClassifier class
neigh1.fit(X1_train, y1_train) # training the object with TR 
prediction1 = neigh1.predict(x1_test) # predicting the labels of TE data
m.accuracy_score(y1_test, prediction1) # calculating accuracy of sklearn KNN classifier

0.8055555555555556

In [47]:
conf_matrix_SkLearn_KNN_Dataset2 = confusion_matrix(y1_test, prediction1)
df4 = pd.DataFrame(conf_matrix_SkLearn_KNN_Dataset2, index=["Actual_0", "Actual_1", "Actual_2"], columns=["Pred_0", "Pred_1", "Pred_2"])
#df4 = pd.DataFrame(conf_matrix_SkLearn_KNN_Dataset2, index=["Actual_0", "Actual_1"], columns=["Pred_0", "Pred_1"])
df4.to_csv("Dataset2_Classifier2.csv")

 SKLearn Tree Classifier

In [48]:
from sklearn import tree
clf = tree.DecisionTreeClassifier() # making an object of the sklearn decision tree class
clf = clf.fit(X1_train, y1_train) # training the object with TR
predictionDecisionTrees1 = clf.predict(x1_test); # calling predict function to predict data (TR)
m.accuracy_score(y1_test,predictionDecisionTrees1) # calculating accuracy of decision tree classifier

0.9444444444444444

In [49]:
conf_matrix_SkLearn_DecisionTrees_Dataset2 = confusion_matrix(y1_test, predictionDecisionTrees1)
df5 = pd.DataFrame(conf_matrix_SkLearn_DecisionTrees_Dataset2, index=["Actual_0", "Actual_1", "Actual_2"], columns=["Pred_0", "Pred_1", "Pred_2"])
df5.to_csv("Dataset2_Classifier3.csv")